# This code contains functions for different source datasets -- most datasets use create_spatial_match_table()
# but a few use a unique function because they are lacking certain attributes (usually fee owner)
#
# The functions use outputs from spatial_matching.py (which mainly uses the Tabulate Intersection and
# Spatial Join tools), as well as attributes form the singlepart version of NEPOS (e.g., Area_Ac)
# to compare NEPOS and source polygons.
#
# For each NEPOS polygon, a code 1-14 is assigned. See Appendix S1 of the NEPOS Update Workflow document
# for more details on the match type codes. The outputs of the create_spatial_match_table() functions
# are combined for each state using combine_match_tables() (also in this script), which produces a table
# of all the NEPOS polygons in the state by FinalID2 (singlepart unique ID) and the corresponding match codes
# for all source polygons relevant to the state. This final output is what is used in later scripts to
# update geometry and attributes ("the match table").
#
# These functions are called by source() in find_matching_polygons.R
#
# Lucy Lee, 7/2025

library(foreign)
library(dplyr)
library(ggplot2)

# Define 'not in' operator -- useful for subsetting
`%!in%` <- Negate(`%in%`)

## Function to create spatial match table, and save 'long' and 'short' copies of the result as a CSV
# The short version is just the highest level results, while the long version contains teh acre ratio and % overlap
# Inputs are the four table outputs from spatial joins and 1 table output from Tabulate Intersection
# All table inputs are generated by 05_spatial_matching.py and must be either in the wd set above or input with a full path
# All CSV and DBF arguments (first 6 args) are expected as file paths - the function will open them into DFs.
#    - join_table1 = 1:1 join with POS polygons as target fc and source points as join fc
#    - join_table2 = 1:1 join with source polygons as target fc and POS points as join fc
#    - join_table3 = 1:m join with POS polygons as target fc and source points as join fc
#    - join_table4 = 1:m join with source polygons as target fc and POS points as join fc
#    - pct_overlap_table = table resulting from Tabulate Intersection
#    - nepos = DBF of relevant POS version
#    - source = description of the data source to include in output file name (e.g. massgis, tnc, nced, nh_granit)
#    - state = leave NULL if New England wide (NCED, TNC), add state abbreviation if state data source
#              this is used for subsetting NEPOS to compare completion of match table
#    - save_csv = TRUE or FALSE whether CSVs should be saved or not
# The function returns main_df for further analysis and/or visualization, so saving CSV is not necessary (e.g. during iteration)
# This function is suitable for all sources that have fee owner info (i.e., all sources except NCED)
create_spatial_match_table <- function(join_table1, join_table2, join_table3, join_table4,
                                       pct_overlap_table, nepos, source = 'source', state = NULL, save_csv = TRUE) {
  #### STEP 1: Read in and prep tables ####
  # Spatial join tables -- all joins only kept common rows, which means that only rows in the target fc
  # that had a spatial match in the join fc are present -- if a row in the target fc (polygon) is not
  # present, it did not have a join fc point inside it
  # 1:1 joins
  wd <- getwd()
  df1 <- read.dbf(paste(wd, join_table1, sep = '/'), as.is = TRUE)
  df2 <- read.dbf(paste(wd, join_table2, sep = '/'), as.is = TRUE)
  
  # 1:many joins
  df3 <- read.dbf(paste(wd, join_table3, sep = '/'), as.is = TRUE)
  df4 <- read.dbf(paste(wd, join_table4, sep = '/'), as.is = TRUE)
  
  # Percent overlap table (TabulateIntersection output)
  pct.df <- read.csv(paste(wd, pct_overlap_table, sep = '/'), stringsAsFactors = FALSE)
  
  # DBF copy of the single part NEPOS attribute table
  # Since we only kept common rows in the spatial joins, we need to use this to identify NEPOS polygons
  # that did not have a match in any of the spatial joins
  nepos <- read.dbf(paste(wd, nepos, sep = '/'), as.is = TRUE)
  
  # Rename columns AreaName and FeeOwner columns to avoid confusion
  # These are used to compare attributes for some match codes
  df1 <- rename(df1, NEPOS_FeeOwner = FeeOwner, NEPOS_AreaName = AreaName, SRC_FeeOwner = FeeOwner_1, SRC_AreaName = AreaName_1)
  df2 <- rename(df2, NEPOS_FeeOwner = FeeOwner_1, NEPOS_AreaName = AreaName_1, SRC_FeeOwner = FeeOwner, SRC_AreaName = AreaName)
  
  # Calculate acre ratio in each spatial join table -- NEPOS:source -- Area_Ac/acres
  df1$ac_rat <- df1$Area_Ac / df1$acres
  df2$ac_rat <- df2$Area_Ac / df2$acres
  df3$ac_rat <- df3$Area_Ac / df3$acres
  df4$ac_rat <- df4$Area_Ac / df4$acres
  
  # FinalID2 column of pct.csv formatted strangely, need to correct it
  colnames(pct.df)[1] <- 'FinalID2'
  
  # Subset each table to only needed columns -- UID2, FinalID2, Join_Count, ac_rat
  # For % overlap table -- UID2, FinalID2, PERCENTAGE
  df1 <- df1[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'NEPOS_AreaName', 'NEPOS_FeeOwner', 'SRC_AreaName', 'SRC_FeeOwner')]
  df2 <- df2[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'SRC_AreaName', 'SRC_FeeOwner', 'NEPOS_AreaName', 'NEPOS_FeeOwner')]
  df3 <- df3[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  df4 <- df4[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  pct.df <- pct.df[, c('FinalID2', 'UID2', 'PERCENTAGE')]
  #pct.df$UID2 <- as.character(pct.df$UID2)   # Not sure why it's an integer in this file but it is...
  
  # Adjust the area/owner name columns
  df1$NEPOS_AreaName <- tolower(df1$NEPOS_AreaName)
  df1$NEPOS_FeeOwner <- tolower(df1$NEPOS_FeeOwner)
  df1$SRC_AreaName <- tolower(df1$SRC_AreaName)
  df1$SRC_FeeOwner <- tolower(df1$SRC_FeeOwner)
  
  df2$NEPOS_AreaName <- tolower(df2$NEPOS_AreaName)
  df2$NEPOS_FeeOwner <- tolower(df2$NEPOS_FeeOwner)
  df2$SRC_AreaName <- tolower(df2$SRC_AreaName)
  df2$SRC_FeeOwner <- tolower(df2$SRC_FeeOwner)
  
  #### STEP 2: Process polygon pairs where Joint_Count = 1 w/ bidirectional centroid containment ####
  # Join the 1:1 spatial join outputs
  # Parameter notes: inner join retains all rows in df1 (POS as target dataset)
  #    Using both UIDs as join fields ensures that the join happens correctly, and that we're
  #       only retrieving rows where centroid containment goes both directions between the polygon pair
  #    And joining only where Join_Count = 1 limits the join to only those rows
  #    (join counts greater than 1 will be handled later, along with 1:many join outputs)
  join1 <- inner_join(df1[df1$Join_Count == 1, ], df2[df2$Join_Count == 1, ], by = c('FinalID2', 'UID2'))
  
  # Drop unneeded columns and rename columns
  join1 <- join1[, -c(9:14)]
  colnames(join1) <- c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'NEPOS_AreaName', 'NEPOS_FeeOwner', 'SRC_AreaName', 'SRC_FeeOwner')
  
  # Assign ac_rat_match based on whether the acre ratio is between 0.9-1.1 or not
  join1$ac_rat_match <- ifelse(join1$ac_rat >= 0.9 & join1$ac_rat <= 1.1, 1, 0)
  
  # Join the percent overlap table and add a column describing if the % overlap
  # falls within the threshold range
  join1 <- left_join(join1, pct.df, by = c('FinalID2', 'UID2'))
  join1$pct_overlap_match <- ifelse(join1$PERCENTAGE >= 90.0 & join1$PERCENTAGE <= 110.0, 1, 0)
  
  # Remove rows where either ac_rat_match or pct_overlap_match are NA
  join1 <- join1[!is.na(join1$ac_rat_match), ]
  join1 <- join1[!is.na(join1$pct_overlap_match), ]
  
  # Add 'match_type' field to describe the nature of the match for these polygons:
  # Bi-directional centroid match is present if the rows are in the join1 table, because we used both IDs to do the join
  # Acre ratio match is stored in ac_rat_match
  # Percent overlap match is stored in pct_overlap_match
  # Then based on the match type, populate 'suggest' column that suggests what action should be taken
  # match_type_code is just to help with plotting/querying because the match_type descriptions are long
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids, area ratio, and % overlap'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type_code'] <- 1
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'suggest'] <- 'Good match - no action needed'
  
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids and area ratio'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type_code'] <- 2 
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids and % overlap'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type_code'] <- 3
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type_code'] <- 4
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  
  #### STEP 3: Process polygon pairs where Join_Count > 1 ####
  # First, look for POS polygons that contain multiple source centroids (df1 and df3)
  # Get IDs of NEPOS that have multiple join -- this means multiple source centroids are within one POS polygon
  multi_join_ids_df1 <- df1[df1$Join_Count > 1, 'FinalID2']
  
  # Extract rows with those IDs from DF3, which contains the 1:many join w/ NEPOS as target
  # These are POS polygons that had multiple source centroids in them
  df3.ss <- df3[df3$FinalID2 %in% multi_join_ids_df1, ]
  
  # Add match type -- here we don't expect ac_rat to match because the join count is > 1
  # So the match is based just on POS containing source centroids
  df3.ss$match_type <- 'POS contains multiple source centroids'
  df3.ss$match_type_code <- 9
  df3.ss$suggest <- '1:many relationship - check geometry'
  df3.ss <- left_join(df3.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Combine 1:1 matches and 1:many matches -- joincols is all the columns for the 'full' output
  # Since df3 and df4 don't have these columns, we need separate sets of column names
  joincols_df1_df2 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 
                        'ac_rat', 'ac_rat_match', 'PERCENTAGE', 'pct_overlap_match')
  joincols_df3_df4 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest',
                        'PERCENTAGE')
  all_matches <- bind_rows(join1[, joincols_df1_df2], df3.ss[, joincols_df3_df4])
  
  # Next, look for POS polygons that that have a many:1 relationship with a source polygon (df2 and df4)
  multi_join_ids_df2 <- df2[df2$Join_Count > 1, 'UID2']
  
  # Get rows with these UID from df4, which contains the 1:many join w/ source as target
  # These are the source polygons that contain multiple POS centroids
  df4.ss <- df4[df4$UID2 %in% multi_join_ids_df2, ]
  
  # Add match type for these rows
  df4.ss$match_type <- 'Source contains multiple POS centroids'
  df4.ss$match_type_code <- 10
  df4.ss$suggest <- '1:many relationship - check geometry'
  df4.ss <- left_join(df4.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Add these to the table of all matches
  all_matches <- bind_rows(all_matches, df4.ss[, joincols_df3_df4])
  
  
  ### STEP 4: Process polygons pairs where there is a 1:1 match but only in one direction ####
  # In other words, each polygon's centroid is not in the other, only one of them has this condition
  # First, look for POS polygons that are in df1 but are not in our all_matches table
  # This means that POS polygon contains a source centroid, but not vice versa
  # First, subset df1 to where Join_Count = 1
  df1.ss <- df1[df1$Join_Count == 1, ]
  
  # Then, exclude any rows in all_matches -- this will leave us with rows where Join_Count = 1 but didn't meet criteria for join1,
  # which included centroid containment in both directions (because we joined by both FinalID2 and UID2)
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  df1.ss <- df1.ss[df1.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  df1.ss <- left_join(df1.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  if (nrow(df1.ss) > 0){
    # Describe acre ratio and percent overlap
    df1.ss$ac_rat_match <- ifelse(df1.ss$ac_rat >= 0.9 & df1.ss$ac_rat <= 1.1, 1, 0) 
    df1.ss$pct_overlap_match <- ifelse(df1.ss$PERCENTAGE >= 90.0 & df1.ss$PERCENTAGE <= 110.0, 1, 0)
    
    # Remove rows where either ac_rat_match or pct_overlap_match are NA
    df1.ss <- df1.ss[!is.na(df1.ss$ac_rat_match), ]
    df1.ss <- df1.ss[!is.na(df1.ss$pct_overlap_match), ]
    
    # Add the match_type and suggest columns
    # For some of these groups, we add additional check b/c centroid containment is only in one direction
    # This suggests a less clear match and we want to check to see if owner or area name match if the acre ratio is very low
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres and % overlap within range.'
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres match but not % overlap.'
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. % overlap match but not acres.'
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. No match for acres & % overlap.'
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
    
    # Join these results to all_matches df
    all_matches <- bind_rows(all_matches, df1.ss[, joincols_df1_df2])
  }
  
  # Repeat this process using df2, with contains source polygons that may contain a POS centroid but not vice versa
  all_matched_ids <- unique(all_matches[, 'FinalID2'])                 # Run this again to account for latest additions
  df2.ss <- df2[df2$Join_Count == 1, ]
  df2.ss <- df2.ss[df2.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  # For the second iteration of matching w/ RI Local, after geometry updates, there was only 1 row in df2.ss
  df2.ss <- left_join(df2.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Describe acre ratio and percent overlap
  df2.ss$ac_rat_match <- ifelse(df2.ss$ac_rat >= 0.9 & df2.ss$ac_rat <= 1.1, 1, 0)
  df2.ss$pct_overlap_match <- ifelse(df2.ss$PERCENTAGE >= 90.0 & df2.ss$PERCENTAGE <= 110.0, 1, 0)
  
  # Remove rows where there is NA for either acre ratio or pct overlap
  df2.ss <- df2.ss[!is.na(df2.ss$ac_rat_match), ]
  df2.ss <- df2.ss[!is.na(df2.ss$pct_overlap_match), ]
  
  if (nrow(df2.ss) > 0){
    # Add the match_type and suggest columns
    df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres and % overlap within range.'
    df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
    df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
    
    df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres match but not % overlap.'
    df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
    df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
    
    df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. % overlap match but not acres.'
    df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
    df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
    
    df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. No match for acres & % overlap.'
    df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
    df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
    
    # Join to all_matches
    all_matches <- bind_rows(all_matches, df2.ss[, joincols_df1_df2])
  }
  
  #### STEP 5: Handle polygon pairs where there is no centroid containment but there is some % overlap ####
  # Get all POS FinalIDs in all_matches
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  
  # Retrieve rows from pct df that have FinalID2 not in all_matched_ids
  pct.df.ss <- pct.df[pct.df$FinalID2 %!in% all_matched_ids, ]
  
  
  # Characterize match type based on % overlap
  # Groupings: >50% overlap, 25-50%, 5-25%, < 5%
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type'] <- '>50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type_code'] <- 11
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type'] <- '20-50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type_code'] <- 12
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type'] <- 'Less than 20% overlap and no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type_code'] <- 13
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'suggest'] <- 'Possibly delete'   # Same 'suggest' value as totally unmatched polygons
  
  # Join these results to all_matches
  join_cols_pct_df <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 'PERCENTAGE')
  all_matches <- bind_rows(all_matches, pct.df.ss[, join_cols_pct_df])
  
  
  #### STEP 6: Handle POS polygons with no match of any kind in source data ####
  # Compare number of unique NEPOS IDs in all_matches and NEPOS
  paste0('Number of unique NEPOS IDs in all_matches: ', length(unique(all_matches$FinalID2)))
  if (state %in% c('NH', 'MA', 'RI', 'CT', 'VT', 'ME')){
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos[nepos$State == state, 'FinalID2']))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else if (is.null(state)) {
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos$FinalID2))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else {
    print('Cannot compare to NEPOS: ensure "state" is either state abbreviation or NULL for New England-wide data')
  }
  
  # In the previous steps, we used the 1:1 join tables to describe spatial relationships where there was a 1:1 match
  # and we used the 1:many join tables to describe the relationships that are not 1:1 matches
  # Spatial relationships not identified yet include 1) POS polygons not matching any source polygon, and 2) source polygons not in POS
  # For this step, we are only interested in #1 -- we will handle identifying new source polygons later using code from Landvest
  # At this point, we are focused on polygons already in NEPOS, looking for geom/attribute changes
  
  # To find POS polygons not matching any source polygon, we need to use the POS single part data
  # because we kept only common rows in the spatial joins. We check for any FinalIDs in NEPOS not in all_matches
  all_matched_ids <- unique(all_matches$FinalID2)
  if (!is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$State == state & nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  } else if (is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  }
  
  unmatched_pos <- data.frame('FinalID2' = unmatched_pos_ids)
  unmatched_pos$match_type <- 'None'
  unmatched_pos$match_type_code <- 0
  unmatched_pos$suggest <- 'Possibly delete'
  
  # Combine all_matches and unmatched_pos into main_df
  main_df <- bind_rows(all_matches, unmatched_pos)
  
  #### STEP 7: CLEAN UP AND SAVE ####
  # Join area and owner names to main_df
  # First, combine df1 and df2
  # Combine owner/area info from df1 and df2
  df1_pos_ids <- unique(df1$FinalID2)
  df2_pos_ids <- unique(df2$FinalID2)
  pos_ids_unique_to_df2 <- df2_pos_ids[df2_pos_ids %!in% df1_pos_ids]   # Get POS polygons only in DF2
  df2.ss2 <- df2[df2$FinalID2 %in% pos_ids_unique_to_df2, ]
  
  area_owner_names <- bind_rows(df1, df2.ss2)
  
  main_df <- left_join(main_df, area_owner_names[, c('FinalID2', 'UID2', 'NEPOS_AreaName', 'NEPOS_FeeOwner', 'SRC_AreaName', 'SRC_FeeOwner')],
                       by = c('FinalID2', 'UID2'))
  
  # Need to account for polygons pairs with very low acre ratio or % overlap that got coded into groups 2-8
  # In some cases, these should not be considered a match
  main_df[main_df$match_type_code %in% c(5, 6, 7, 8) & (main_df$ac_rat < 0.5 | main_df$ac_rat > 1.5) & !is.na(main_df$SRC_AreaName) &
            !is.na(main_df$NEPOS_AreaName) & !is.na(main_df$SRC_FeeOwner) & !is.na(main_df$NEPOS_FeeOwner) &
            (main_df$NEPOS_AreaName != main_df$SRC_AreaName | main_df$NEPOS_FeeOwner != main_df$SRC_FeeOwner), 'match_type_code'] <- 14
  
  # For % overlap, we can include codes 11-13 since these have % overlap calculated but do not have ac_rat
  # Due to not having a match in the spatial joins
  main_df[main_df$match_type_code %in% c(5, 6, 7, 8, 11, 12, 13) & main_df$PERCENTAGE < 20.0 & !is.na(main_df$SRC_AreaName) &
            !is.na(main_df$NEPOS_AreaName) & !is.na(main_df$SRC_FeeOwner) & !is.na(main_df$NEPOS_FeeOwner) &
            (main_df$NEPOS_AreaName != main_df$SRC_AreaName | main_df$NEPOS_FeeOwner != main_df$SRC_FeeOwner), 'match_type_code'] <- 14
  
  # Update the suggest for match type code 14
  main_df[main_df$match_type_code == 14, 'suggest'] <- 'Some match criteria met but poor match and names do not match. Possibly delete.'
  
  # Compare number of unique IDs in main_df and nepos after these additions
  # If the number in all_matches is higher, it could be because of subsetting NEPOS by state (border PAs)
  # Get both the number of unique IDs and the IDs themselves in case needed later
  main_df_ids <- unique(main_df$FinalID2)
  n_main_df_ids <- length(main_df_ids)
  print(paste0('Number of unique NEPOS IDs in main_df: ', n_main_df_ids))
  if (!is.null(state)){
    nepos_ids <- unique(nepos[nepos$State == state, 'FinalID2'])
    n_nepos_ids <- length(nepos_ids)
    paste0('Number of unique IDs in NEPOS: ', n_nepos_ids)
  } else if (is.null(state)){
    nepos_ids <- unique(nepos$FinalID2)
    n_nepos_ids <- length(nepos_ids)
    paste0('Number of unique IDs in NEPOS: ', n_nepos_ids)
  }
  
  # If number of IDs is higher in main_df than in NEPOS, print this and the "extra" FinalIDs
  if (n_main_df_ids > n_nepos_ids){
    print('Number of NEPOS IDs in main_df is higher than in NEPOS. This may be due to border PAs - further investigation needed!')
    extra_ids <- main_df_ids[main_df_ids %!in% nepos_ids]
    print('NEPOS IDs in main_df but not in NEPOS selection:')
    print(extra_ids)
  }
  
  # Save result! One copy w/ ac_ratio and PERCENTAGE and another with just the match_type and suggest columns
  if (save_csv == TRUE) {
    todays_date <- Sys.Date()
    write.csv(main_df, paste0('nepos_', source, '_match_table_', todays_date, '_full.csv'), row.names = F)
    write.csv(main_df[, c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest')],
              paste0('nepos_', source, '_match_table_', todays_date, '_min.csv'), row.names = F)
    print(paste0('Saved spatial match table for NEPOS and ', source, ' in working directory!'))
  }
  
  # Return main_df for graphing of results
  return(main_df)
}

# Because NCED doesn't have fee owner name, only fee owner type
# We modify the usual code to handle this difference
create_spatial_match_table_nced <- function(join_table1, join_table2, join_table3, join_table4,
                                            pct_overlap_table, nepos, source = 'source', state = NULL, save_csv = TRUE) {
  #### STEP 1: Read in and prep tables ####
  # Spatial join tables -- all joins only kept common rows, which means that only rows in the target fc
  # that had a spatial match in the join fc are present -- if a row in the target fc (polygon) is not
  # present, it did not have a join fc point inside it
  # 1:1 joins
  wd <- getwd()
  df1 <- read.dbf(paste(wd, join_table1, sep = '/'), as.is = TRUE)
  df2 <- read.dbf(paste(wd, join_table2, sep = '/'), as.is = TRUE)
  
  # 1:many joins
  df3 <- read.dbf(paste(wd, join_table3, sep = '/'), as.is = TRUE)
  df4 <- read.dbf(paste(wd, join_table4, sep = '/'), as.is = TRUE)
  
  # Percent overlap table
  pct.df <- read.csv(paste(wd, pct_overlap_table, sep = '/'), stringsAsFactors = FALSE)
  colnames(pct.df)[1] <- 'FinalID2'
  
  # DBF copy of the single part NEPOS attribute table
  # Since we only kept common rows in the spatial joins, we need to use this to identify NEPOS polygons
  # that did not have a match in any of the spatial joins
  nepos <- read.dbf(paste(wd, nepos, sep = '/'), as.is = TRUE)
  
  # Rename columns AreaName and FeeOwnType columns to avoid confusion
  # These are used to compare attributes for some match codes
  df1 <- rename(df1, NEPOS_FeeOwnType = FeeOwnType, NEPOS_AreaName = AreaName, SRC_FeeOwnType = FeeOwnTy_1, SRC_AreaName = AreaName_1)
  df2 <- rename(df2, NEPOS_FeeOwnType = FeeOwnTy_1, NEPOS_AreaName = AreaName_1, SRC_FeeOwnType = FeeOwnType, SRC_AreaName = AreaName)
  
  # Calculate acre ratio in each spatial join table -- NEPOS:source -- Area_Ac/acres
  df1$ac_rat <- df1$Area_Ac / df1$acres
  df2$ac_rat <- df2$Area_Ac / df2$acres
  df3$ac_rat <- df3$Area_Ac / df3$acres
  df4$ac_rat <- df4$Area_Ac / df4$acres
  
  # Subset each table to only needed columns -- UID2, FinalID2, Join_Count, ac_rat
  # For % overlap table -- UID2, FinalID2, PERCENTAGE
  df1 <- df1[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'NEPOS_AreaName', 'NEPOS_FeeOwnType', 'SRC_AreaName', 'SRC_FeeOwnType')]
  df2 <- df2[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'SRC_AreaName', 'SRC_FeeOwnType', 'NEPOS_AreaName', 'NEPOS_FeeOwnType')]
  df3 <- df3[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  df4 <- df4[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  pct.df <- pct.df[, c('FinalID2', 'UID2', 'PERCENTAGE')]
  
  # Adjust the area/owner name columns
  df1$NEPOS_AreaName <- tolower(df1$NEPOS_AreaName)
  df1$NEPOS_FeeOwnType <- tolower(df1$NEPOS_FeeOwnType)
  df1$SRC_AreaName <- tolower(df1$SRC_AreaName)
  df1$SRC_FeeOwnType <- tolower(df1$SRC_FeeOwnType)
  
  df2$NEPOS_AreaName <- tolower(df2$NEPOS_AreaName)
  df2$NEPOS_FeeOwnType <- tolower(df2$NEPOS_FeeOwnType)
  df2$SRC_AreaName <- tolower(df2$SRC_AreaName)
  df2$SRC_FeeOwnType <- tolower(df2$SRC_FeeOwnType)
  
  # Remove rows from each table where all columns are NA
  df1 <- df1[rowSums(is.na(df1)) != ncol(df1), ]
  df2 <- df2[rowSums(is.na(df2)) != ncol(df2), ]
  df3 <- df3[rowSums(is.na(df3)) != ncol(df3), ]
  df4 <- df4[rowSums(is.na(df4)) != ncol(df4), ]
  pct.df <- pct.df[rowSums(is.na(pct.df)) != ncol(pct.df), ]
  
  
  #### STEP 2: Process polygon pairs where Joint_Count = 1 w/ bidirectional centroid containment ####
  # Join the 1:1 spatial join outputs
  # Parameter notes: inner join retains all rows in df1 (POS as target dataset)
  #    Using both UIDs as join fields ensures that the join happens correctly, and that we're
  #       only retrieving rows where centroid containment goes both directions between the polygon pair
  #    And joining only where Join_Count = 1 limits the join to only those rows
  #    (join counts greater than 1 will be handled later, along with 1:many join outputs)
  join1 <- inner_join(df1[df1$Join_Count == 1, ], df2[df2$Join_Count == 1, ], by = c('FinalID2', 'UID2'))
  
  # Drop unneeded columns and rename columns
  join1 <- join1[, -c(9:14)]
  colnames(join1) <- c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'NEPOS_AreaName', 'NEPOS_FeeOwnType', 'SRC_AreaName', 'SRC_FeeOwnType')
  
  # Assign ac_rat_match based on whether the acre ratio is between 0.9-1.1 or not
  join1$ac_rat_match <- ifelse(join1$ac_rat >= 0.9 & join1$ac_rat <= 1.1, 1, 0)
  
  # Join the percent overlap table and add a column describing if the % overlap
  # falls within the threshold range
  join1 <- left_join(join1, pct.df, by = c('FinalID2', 'UID2'))
  join1$pct_overlap_match <- ifelse(join1$PERCENTAGE >= 90.0 & join1$PERCENTAGE <= 110.0, 1, 0)
  
  # Add 'match_type' field to describe the nature of the match for these polygons:
  # Bi-directional centroid match is present if the rows are in the join1 table, because we used both IDs to do the join
  # Acre ratio match is stored in ac_rat_match
  # Percent overlap match is stored in pct_overlap_match
  # Then based on the match type, populate 'suggest' column that suggests what action should be taken
  # match_type_code is just to help with plotting/querying because the match_type descriptions are long
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids, area ratio, and % overlap'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type_code'] <- 1
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'suggest'] <- 'Good match - no action needed'
  
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids and area ratio'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type_code'] <- 2 
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids and % overlap'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type_code'] <- 3
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type_code'] <- 4
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  
  #### STEP 3: Process polygon pairs where Join_Count > 1 ####
  # First, look for POS polygons that contain multiple source centroids (df1 and df3)
  # Get IDs of NEPOS that have multiple join -- this means multiple MA centroids are within one POS polygon
  multi_join_ids_df1 <- df1[df1$Join_Count > 1, 'FinalID2']
  
  # Extract rows with those IDs from DF3, which contains the 1:many join w/ NEPOS as target
  # These are POS polygons that had multiple MA centroids in them
  df3.ss <- df3[df3$FinalID2 %in% multi_join_ids_df1, ]
  
  # Add match type -- here we don't expect ac_rat to match because the join count is > 1
  # So the match is based just on POS containing source centroid
  df3.ss$match_type <- 'POS contains multiple source centroids'
  df3.ss$match_type_code <- 9
  df3.ss$suggest <- '1:many relationship - check geometry'
  df3.ss <- left_join(df3.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Combine 1:1 matches and 1:many matches -- joincols is all the columns for the 'full' output
  # Since df3 and df4 don't have these columns, we need separate sets of column names
  joincols_df1_df2 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 
                        'ac_rat', 'ac_rat_match', 'PERCENTAGE', 'pct_overlap_match')
  joincols_df3_df4 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest',
                        'PERCENTAGE')
  all_matches <- bind_rows(join1[, joincols_df1_df2], df3.ss[, joincols_df3_df4])
  
  # Next, look for POS polygons that that have a many:1 relationship with a source polygon (df2 and df4)
  multi_join_ids_df2 <- df2[df2$Join_Count > 1, 'UID2']
  
  # Get rows with these UID from df4, which contains the 1:many join w/ MA as target
  # These are the source polygons that contain multiple POS centroids
  df4.ss <- df4[df4$UID2 %in% multi_join_ids_df2, ]
  
  # Add match type for these rows
  df4.ss$match_type <- 'Source contains multiple POS centroids'
  df4.ss$match_type_code <- 10
  df4.ss$suggest <- '1:many relationship - check geometry'
  df4.ss <- left_join(df4.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Add these to the table of all matches
  all_matches <- bind_rows(all_matches, df4.ss[, joincols_df3_df4])
  
  
  ### STEP 4: Process polygons pairs where there is a 1:1 match but only in one direction ####
  # In other words, each polygon's centroid is not in the other, only one of them has this condition
  # First, look for POS polygons that are in df1 but are not in our all_matches table
  # This means that POS polygon contains a source centroid, but not vice versa
  # First, subset df1 to where Join_Count = 1
  df1.ss <- df1[df1$Join_Count == 1, ]
  
  # Then, exclude any rows in all_matches -- this will leave us with rows where Join_Count = 1 but didn't meet criteria for join1,
  # which included centroid containment in both directions (because we joined by both FinalID2 and UID2)
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  df1.ss <- df1.ss[df1.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  df1.ss <- left_join(df1.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Remove rows where PERCENTAGE is NA
  df1.ss <- df1.ss[!is.na(df1.ss$PERCENTAGE), ]
  
  # Describe acre ratio and percent overlap
  df1.ss$ac_rat_match <- ifelse(df1.ss$ac_rat >= 0.9 & df1.ss$ac_rat <= 1.1, 1, 0) 
  df1.ss$pct_overlap_match <- ifelse(df1.ss$PERCENTAGE >= 90.0 & df1.ss$PERCENTAGE <= 110.0, 1, 0)
  
  # Add the match_type and suggest columns
  # For some of these groups, we add additional check b/c centroid containment is only in one direction
  # This suggests a less clear match and we want to check to see if owner or area name match if the acre ratio is very low
  df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres and % overlap within range.'
  df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
  df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
  
  df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres match but not % overlap.'
  df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
  df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. % overlap match but not acres.'
  df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
  df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. No match for acres & % overlap.'
  df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
  df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
  
  # Join these results to all_matches df
  all_matches <- bind_rows(all_matches, df1.ss[, joincols_df1_df2])
  
  # Repeat this process using df2, with contains source polygons that may contain a POS centroid but not vice versa
  all_matched_ids <- unique(all_matches[, 'FinalID2'])                 # Run this again to account for latest additions
  df2.ss <- df2[df2$Join_Count == 1, ]
  df2.ss <- df2.ss[df2.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  df2.ss <- left_join(df2.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Describe acre ratio and percent overlap
  df2.ss$ac_rat_match <- ifelse(df2.ss$ac_rat >= 0.9 & df2.ss$ac_rat <= 1.1, 1, 0)
  df2.ss$pct_overlap_match <- ifelse(df2.ss$PERCENTAGE >= 90.0 & df2.ss$PERCENTAGE <= 110.0, 1, 0)
  
  # Add the match_type and suggest columns
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres and % overlap within range.'
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres match but not % overlap.'
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. % overlap match but not acres.'
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. No match for acres & % overlap.'
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
  
  # Join to all_matches
  all_matches <- bind_rows(all_matches, df2.ss[, joincols_df1_df2])
  
  
  #### STEP 5: Handle polygon pairs where there is no centroid containment but there is some % overlap ####
  # Get all POS FinalIDs in all_matches
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  
  # Retrieve rows from pct df that have FinalID2 not in all_matched_ids
  pct.df.ss <- pct.df[pct.df$FinalID2 %!in% all_matched_ids, ]
  
  # Characterize match type based on % overlap
  # Groupings: >50% overlap, 25-50%, 5-25%, < 5%
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type'] <- '>50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type_code'] <- 11
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type'] <- '20-50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type_code'] <- 12
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type'] <- 'Less than 20% overlap and no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type_code'] <- 13
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'suggest'] <- 'Possibly delete'   # Same 'suggest' value as totally unmatched polygons
  
  # Join these results to all_matches
  join_cols_pct_df <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 'PERCENTAGE')
  all_matches <- bind_rows(all_matches, pct.df.ss[, join_cols_pct_df])
  
  
  #### STEP 6: Handle POS polygons with no match of any kind in source data ####
  # Compare number of unique NEPOS IDs in all_matches and NEPOS
  paste0('Number of unique NEPOS IDs in all_matches: ', length(unique(all_matches$FinalID2)))
  if (state %in% c('NH', 'MA', 'RI', 'CT', 'VT', 'ME')){
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos[nepos$State == state, 'FinalID2']))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else if (is.null(state)) {
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos$FinalID2))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else {
    print('Cannot compare to NEPOS: ensure "state" is either state abbreviation or NULL for New England-wide data')
  }
  
  # In the previous steps, we used the 1:1 join tables to describe spatial relationships where there was a 1:1 match
  # and we used the 1:many join tables to describe the relationships that are not 1:1 matches
  # Spatial relationships not identified yet include 1) POS polygons not matching any source polygon, and 2) source polygons not in POS
  # For this step, we are only interested in #1 -- we will handle identifying new source polygons later using code from Landvest
  # At this point, we are focused on polygons already in NEPOS, looking for geom/attribute changes
  
  # To find POS polygons not matching any source polygon, we need to use the POS single part data
  # because we kept only common rows in the spatial joins. We check for any FinalIDs in NEPOS not in all_matches
  all_matched_ids <- unique(all_matches$FinalID2)
  if (!is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$State == state & nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  } else if (is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  }
  
  ## IS IT POSSIBLE TO INCORPORATE % OVERLAP TABLE HERE TO ACCOUNT FOR INSTANCES OF OVERLAP BUT NOT CENTROID CONTAINMENT??
  # Check to see if this is useful -- need to check Code 0 in map and see what these look like
  unmatched_pos <- data.frame('FinalID2' = unmatched_pos_ids)
  unmatched_pos$match_type <- 'None'
  unmatched_pos$match_type_code <- 0
  unmatched_pos$suggest <- 'Possibly delete'
  
  # Combine all_matches and unmatched_pos into main_df
  main_df <- bind_rows(all_matches, unmatched_pos)
  
  #### STEP 7: CLEAN UP AND SAVE ####
  # Join area and owner names to main_df
  # First, combine df1 and df2
  # Combine owner/area info from df1 and df2
  df1_pos_ids <- unique(df1$FinalID2)
  df2_pos_ids <- unique(df2$FinalID2)
  pos_ids_unique_to_df2 <- df2_pos_ids[df2_pos_ids %!in% df1_pos_ids]   # Get POS polygons only in DF2
  df2.ss2 <- df2[df2$FinalID2 %in% pos_ids_unique_to_df2, ]
  
  area_owner_names <- bind_rows(df1, df2.ss2)
  
  main_df <- left_join(main_df, area_owner_names[, c('FinalID2', 'UID2', 'NEPOS_AreaName', 'NEPOS_FeeOwnType', 'SRC_AreaName', 'SRC_FeeOwnType')],
                       by = c('FinalID2', 'UID2'))
  
  # Need to account for polygons pairs with very low acre ratio or % overlap that got coded into groups 2-8
  # In some cases, these should not be considered a match
  main_df[main_df$match_type_code %in% c(5, 6, 7, 8) & (main_df$ac_rat < 0.5 | main_df$ac_rat > 1.5) & !is.na(main_df$SRC_AreaName) &
            !is.na(main_df$NEPOS_AreaName) & !is.na(main_df$SRC_FeeOwnType) & !is.na(main_df$NEPOS_FeeOwnType) &
            (main_df$NEPOS_AreaName != main_df$SRC_AreaName | main_df$NEPOS_FeeOwnType != main_df$SRC_FeeOwnType), 'match_type_code'] <- 14
  
  # For % overlap, we can include codes 11-13 since these have % overlap calculated but do not have ac_rat
  # Due to not having a match in the spatial joins
  main_df[main_df$match_type_code %in% c(5, 6, 7, 8, 11, 12, 13) & main_df$PERCENTAGE < 20.0 & !is.na(main_df$SRC_AreaName) &
            !is.na(main_df$NEPOS_AreaName) & !is.na(main_df$SRC_FeeOwnType) & !is.na(main_df$NEPOS_FeeOwnType) &
            (main_df$NEPOS_AreaName != main_df$SRC_AreaName | main_df$NEPOS_FeeOwnType != main_df$SRC_FeeOwnType), 'match_type_code'] <- 14
  
  # Update the suggest for match type code 14
  main_df[main_df$match_type_code == 14, 'suggest'] <- 'Some match criteria met but poor match and names do not match. Possibly delete.'
  
  # Compare number of unique IDs in main_df and nepos after these additions
  # If the number in all_matches is higher, it could be because of subsetting NEPOS by state (border PAs)
  # Get both the number of unique IDs and the IDs themselves in case needed later
  main_df_ids <- unique(main_df$FinalID2)
  n_main_df_ids <- length(main_df_ids)
  print(paste0('Number of unique NEPOS IDs in main_df: ', n_main_df_ids))
  if (!is.null(state)){
    nepos_ids <- unique(nepos[nepos$State == state, 'FinalID2'])
    n_nepos_ids <- length(nepos_ids)
    paste0('Number of unique IDs in NEPOS: ', n_nepos_ids)
  } else if (is.null(state)){
    nepos_ids <- unique(nepos$FinalID2)
    n_nepos_ids <- length(nepos_ids)
    paste0('Number of unique IDs in NEPOS: ', n_nepos_ids)
  }
  
  # If number of IDs is higher in main_df than in NEPOS, print this and the "extra" FinalIDs
  if (n_main_df_ids > n_nepos_ids){
    print('Number of NEPOS IDs in main_df is higher than in NEPOS. This may be due to border PAs - further investigation needed!')
    extra_ids <- main_df_ids[main_df_ids %!in% nepos_ids]
    print('NEPOS IDs in main_df but not in NEPOS selection:')
    print(extra_ids)
  }
  
  # Save result! One copy w/ ac_ratio and PERCENTAGE and another with just the match_type and suggest columns
  if (save_csv == TRUE) {
    todays_date <- Sys.Date()
    write.csv(main_df, paste0('nepos_', source, '_match_table_', todays_date, '_full.csv'), row.names = F)
    write.csv(main_df[, c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest')],
              paste0('nepos_', source, '_match_table_', todays_date, '_min.csv'), row.names = F)
    print(paste0('Saved spatial match table for NEPOS and ', source, ' in working directory!'))
  }
  
  # Return main_df for graphing of results
  return(main_df)
}


# Spatial matching with the deleted_polygons layer
# This function produces a match table with the deleted polygons layer which we use to remove polygons that
# were previously deleted from NEPOS. The table produced by this function is joined
# to NEPOS and each codes are checked manually. In this case we're usually only concerned with
# the very good matches (codes 1-4 or so) because these indicate that NEPOS is a good match
# for a previously deleted polygon. The reason for checking these manually is that sometimes polygons
# are deleted that we then want to keep -- it's good to be able to scan the attributes of the polygons
# to be deleted to make sure none seem like ones we would now want to keep.
#
# An important difference in this code is that in calculating ac_rat, the two area fields are both
# named Area_Ac bc the deleted polygons layer is NEPOS data. As opposed to other layers where NEPOS
# is Area_Ac and the source is acres. This affects the calculation of ac_rat, so the deleted polygons
# matching needs its own function OR needs to have 'acres' added as a field and automatically updated
# somehow in order to use the general create_spatial_match_table function used for most sources.
create_spatial_match_table_deleted <- function(join_table1, join_table2, join_table3, join_table4,
                                               pct_overlap_table, nepos, source = 'source', state = NULL, save_csv = TRUE) {
  #### STEP 1: Read in and prep tables ####
  # Spatial join tables -- all joins only kept common rows, which means that only rows in the target fc
  # that had a spatial match in the join fc are present -- if a row in the target fc (polygon) is not
  # present, it did not have a join fc point inside it
  # 1:1 joins
  wd <- getwd()
  df1 <- read.dbf(paste(wd, join_table1, sep = '/'), as.is = TRUE)
  df2 <- read.dbf(paste(wd, join_table2, sep = '/'), as.is = TRUE)
  
  # 1:many joins
  df3 <- read.dbf(paste(wd, join_table3, sep = '/'), as.is = TRUE)
  df4 <- read.dbf(paste(wd, join_table4, sep = '/'), as.is = TRUE)
  
  # Percent overlap table
  pct.df <- read.csv(paste(wd, pct_overlap_table, sep = '/'), stringsAsFactors = FALSE)
  
  # DBF copy of the single part NEPOS attribute table
  # Since we only kept common rows in the spatial joins, we need to use this to identify NEPOS polygons
  # that did not have a match in any of the spatial joins
  nepos <- read.dbf(paste(wd, nepos, sep = '/'), as.is = TRUE)
  
  # Rename columns AreaName and FeeOwner columns to avoid confusion
  # These are used to compare attributes for some match codes
  df1 <- rename(df1, NEPOS_FeeOwner = FeeOwner, NEPOS_AreaName = AreaName, SRC_FeeOwner = FeeOwner_1, SRC_AreaName = AreaName_1)
  df2 <- rename(df2, NEPOS_FeeOwner = FeeOwner_1, NEPOS_AreaName = AreaName_1, SRC_FeeOwner = FeeOwner, SRC_AreaName = AreaName)
  
  # Calculate acre ratio in each spatial join table -- NEPOS:source
  # Unlike other iterations of this script, both deleted_polygons and NEPOS have Area_Ac as the area field
  # which one is Area_Ac and Area_Ac_1 in the joins depends on which dataset is first in the join
  # For tables where POS is first, Area_Ac is the NEPOS area
  # For tables where deleted_polygons, is first, Area_Ac_1 is the NEPOS area
  df1$ac_rat <- df1$Area_Ac / df1$Area_Ac_1
  df2$ac_rat <- df2$Area_Ac_1 / df2$Area_Ac
  df3$ac_rat <- df3$Area_Ac / df3$Area_Ac_1
  df4$ac_rat <- df4$Area_Ac_1 / df4$Area_Ac
  
  # FinalID2 column of pct.csv formatted strangely, need to correct it
  colnames(pct.df)[1] <- 'FinalID2'
  
  # Subset each table to only needed columns -- UID2, FinalID2, Join_Count, ac_rat
  # For % overlap table -- UID2, FinalID2, PERCENTAGE
  df1 <- df1[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'NEPOS_AreaName', 'NEPOS_FeeOwner', 'SRC_AreaName', 'SRC_FeeOwner')]
  df2 <- df2[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'SRC_AreaName', 'SRC_FeeOwner', 'NEPOS_AreaName', 'NEPOS_FeeOwner')]
  df3 <- df3[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  df4 <- df4[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  pct.df <- pct.df[, c('FinalID2', 'UID2', 'PERCENTAGE')]
  pct.df$UID2 <- as.character(pct.df$UID2)   # Not sure why it's an integer in this file but it is...
  
  # Adjust the area/owner name columns
  df1$NEPOS_AreaName <- tolower(df1$NEPOS_AreaName)
  df1$NEPOS_FeeOwner <- tolower(df1$NEPOS_FeeOwner)
  df1$SRC_AreaName <- tolower(df1$SRC_AreaName)
  df1$SRC_FeeOwner <- tolower(df1$SRC_FeeOwner)
  
  df2$NEPOS_AreaName <- tolower(df2$NEPOS_AreaName)
  df2$NEPOS_FeeOwner <- tolower(df2$NEPOS_FeeOwner)
  df2$SRC_AreaName <- tolower(df2$SRC_AreaName)
  df2$SRC_FeeOwner <- tolower(df2$SRC_FeeOwner)
  
  #### STEP 2: Process polygon pairs where Joint_Count = 1 w/ bidirectional centroid containment ####
  # Join the 1:1 spatial join outputs
  # Parameter notes: inner join retains all rows in df1 (POS as target dataset)
  #    Using both UIDs as join fields ensures that the join happens correctly, and that we're
  #       only retrieving rows where centroid containment goes both directions between the polygon pair
  #    And joining only where Join_Count = 1 limits the join to only those rows
  #    (join counts greater than 1 will be handled later, along with 1:many join outputs)
  join1 <- inner_join(df1[df1$Join_Count == 1, ], df2[df2$Join_Count == 1, ], by = c('FinalID2', 'UID2'))
  
  # Drop unneeded columns and rename columns
  join1 <- join1[, -c(9:14)]
  colnames(join1) <- c('FinalID2', 'UID2', 'Join_Count', 'ac_rat', 'NEPOS_AreaName', 'NEPOS_FeeOwner', 'SRC_AreaName', 'SRC_FeeOwner')
  
  # Assign ac_rat_match based on whether the acre ratio is between 0.9-1.1 or not
  join1$ac_rat_match <- ifelse(join1$ac_rat >= 0.9 & join1$ac_rat <= 1.1, 1, 0)
  
  # Join the percent overlap table and add a column describing if the % overlap
  # falls within the threshold range
  join1 <- left_join(join1, pct.df, by = c('FinalID2', 'UID2'))
  join1$pct_overlap_match <- ifelse(join1$PERCENTAGE >= 90.0 & join1$PERCENTAGE <= 110.0, 1, 0)
  
  # Remove rows where either ac_rat_match or pct_overlap_match are NA
  join1 <- join1[!is.na(join1$ac_rat_match), ]
  join1 <- join1[!is.na(join1$pct_overlap_match), ]
  
  # Add 'match_type' field to describe the nature of the match for these polygons:
  # Bi-directional centroid match is present if the rows are in the join1 table, because we used both IDs to do the join
  # Acre ratio match is stored in ac_rat_match
  # Percent overlap match is stored in pct_overlap_match
  # Then based on the match type, populate 'suggest' column that suggests what action should be taken
  # match_type_code is just to help with plotting/querying because the match_type descriptions are long
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids, area ratio, and % overlap'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type_code'] <- 1
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'suggest'] <- 'Good match - no action needed'
  
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids and area ratio'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type_code'] <- 2 
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids and % overlap'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type_code'] <- 3
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type_code'] <- 4
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  #### STEP 3: Process polygon pairs where Join_Count > 1 ####
  # First, look for POS polygons that contain multiple source centroids (df1 and df3)
  # Get IDs of NEPOS that have multiple join -- this means multiple MA centroids are within one POS polygon
  multi_join_ids_df1 <- df1[df1$Join_Count > 1, 'FinalID2']
  
  # Extract rows with those IDs from DF3, which contains the 1:many join w/ NEPOS as target
  # These are POS polygons that had multiple MA centroids in them
  df3.ss <- df3[df3$FinalID2 %in% multi_join_ids_df1, ]
  
  # Add match type -- here we don't expect ac_rat to match because the join count is > 1
  # So the match is based just on POS containing source centroid
  df3.ss$match_type <- 'POS contains multiple source centroids'
  df3.ss$match_type_code <- 9
  df3.ss$suggest <- '1:many relationship - check geometry'
  
  # Combine 1:1 matches and 1:many matches -- joincols is all the columns for the 'full' output
  # Since df3 and df4 don't have these columns, we need separate sets of column names
  joincols_df1_df2 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 
                        'ac_rat', 'ac_rat_match', 'PERCENTAGE', 'pct_overlap_match')
  joincols_df3_df4 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest')
  all_matches <- bind_rows(join1[, joincols_df1_df2], df3.ss[, joincols_df3_df4])
  
  # Next, look for POS polygons that that have a many:1 relationship with a source polygon (df2 and df4)
  multi_join_ids_df2 <- df2[df2$Join_Count > 1, 'UID2']
  
  # Get rows with these UID from df4, which contains the 1:many join w/ MA as target
  # These are the source polygons that contain multiple POS centroids
  df4.ss <- df4[df4$UID2 %in% multi_join_ids_df2, ]
  
  # Add match type for these rows
  df4.ss$match_type <- 'Source contains multiple POS centroids'
  df4.ss$match_type_code <- 10
  df4.ss$suggest <- '1:many relationship - check geometry'
  
  # Add these to the table of all matches
  all_matches <- bind_rows(all_matches, df4.ss[, joincols_df3_df4])
  
  
  ### STEP 4: Process polygons pairs where there is a 1:1 match but only in one direction ####
  # In other words, each polygon's centroid is not in the other, only one of them has this condition
  # First, look for POS polygons that are in df1 but are not in our all_matches table
  # This means that POS polygon contains a source centroid, but not vice versa
  # First, subset df1 to where Join_Count = 1
  df1.ss <- df1[df1$Join_Count == 1, ]
  
  # Then, exclude any rows in all_matches -- this will leave us with rows where Join_Count = 1 but didn't meet criteria for join1,
  # which included centroid containment in both directions (because we joined by both FinalID2 and UID2)
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  df1.ss <- df1.ss[df1.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  df1.ss <- left_join(df1.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  if (nrow(df1.ss) > 0){
    # Describe acre ratio and percent overlap
    df1.ss$ac_rat_match <- ifelse(df1.ss$ac_rat >= 0.9 & df1.ss$ac_rat <= 1.1, 1, 0) 
    df1.ss$pct_overlap_match <- ifelse(df1.ss$PERCENTAGE >= 90.0 & df1.ss$PERCENTAGE <= 110.0, 1, 0)
    
    # Remove rows where either ac_rat_match or pct_overlap_match are NA
    df1.ss <- df1.ss[!is.na(df1.ss$ac_rat_match), ]
    df1.ss <- df1.ss[!is.na(df1.ss$pct_overlap_match), ]
    
    # Add the match_type and suggest columns
    # For some of these groups, we add additional check b/c centroid containment is only in one direction
    # This suggests a less clear match and we want to check to see if owner or area name match if the acre ratio is very low
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres and % overlap within range.'
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres match but not % overlap.'
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. % overlap match but not acres.'
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. No match for acres & % overlap.'
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
    
    # Join these results to all_matches df
    all_matches <- bind_rows(all_matches, df1.ss[, joincols_df1_df2])
  }
  
  # Repeat this process using df2, with contains source polygons that may contain a POS centroid but not vice versa
  all_matched_ids <- unique(all_matches[, 'FinalID2'])                 # Run this again to account for latest additions
  df2.ss <- df2[df2$Join_Count == 1, ]
  df2.ss <- df2.ss[df2.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  # For the second iteration of matching w/ RI Local, after geometry updates, there was only 1 row in df2.ss
  df2.ss <- left_join(df2.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Describe acre ratio and percent overlap
  df2.ss$ac_rat_match <- ifelse(df2.ss$ac_rat >= 0.9 & df2.ss$ac_rat <= 1.1, 1, 0)
  df2.ss$pct_overlap_match <- ifelse(df2.ss$PERCENTAGE >= 90.0 & df2.ss$PERCENTAGE <= 110.0, 1, 0)
  
  # Remove rows where there is NA for either acre ratio or pct overlap
  df2.ss <- df2.ss[!is.na(df2.ss$ac_rat_match), ]
  df2.ss <- df2.ss[!is.na(df2.ss$pct_overlap_match), ]
  
  # Add the match_type and suggest columns
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres and % overlap within range.'
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres match but not % overlap.'
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. % overlap match but not acres.'
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. No match for acres & % overlap.'
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
  
  # Join to all_matches
  all_matches <- bind_rows(all_matches, df2.ss[, joincols_df1_df2])
  
  
  #### STEP 5: Handle polygon pairs where there is no centroid containment but there is some % overlap ####
  # Get all POS FinalIDs in all_matches
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  
  # Retrieve rows from pct df that have FinalID2 not in all_matched_ids
  pct.df.ss <- pct.df[pct.df$FinalID2 %!in% all_matched_ids, ]
  
  
  # Characterize match type based on % overlap
  # Groupings: >50% overlap, 25-50%, 5-25%, < 5%
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type'] <- '>50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type_code'] <- 11
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type'] <- '20-50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type_code'] <- 12
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type'] <- 'Less than 20% overlap and no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type_code'] <- 13
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'suggest'] <- 'Possibly delete'   # Same 'suggest' value as totally unmatched polygons
  
  # Join these results to all_matches
  join_cols_pct_df <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 'PERCENTAGE')
  all_matches <- bind_rows(all_matches, pct.df.ss[, join_cols_pct_df])
  
  
  #### STEP 6: Handle POS polygons with no match of any kind in source data ####
  # Compare number of unique NEPOS IDs in all_matches and NEPOS
  paste0('Number of unique NEPOS IDs in all_matches: ', length(unique(all_matches$FinalID2)))
  if (state %in% c('NH', 'MA', 'RI', 'CT', 'VT', 'ME')){
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos[nepos$State == state, 'FinalID2']))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else if (is.null(state)) {
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos$FinalID2))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else {
    print('Cannot compare to NEPOS: ensure "state" is either state abbreviation or NULL for New England-wide data')
  }
  
  # In the previous steps, we used the 1:1 join tables to describe spatial relationships where there was a 1:1 match
  # and we used the 1:many join tables to describe the relationships that are not 1:1 matches
  # Spatial relationships not identified yet include 1) POS polygons not matching any source polygon, and 2) source polygons not in POS
  # For this step, we are only interested in #1 -- we will handle identifying new source polygons later using code from Landvest
  # At this point, we are focused on polygons already in NEPOS, looking for geom/attribute changes
  
  # To find POS polygons not matching any source polygon, we need to use the POS single part data
  # because we kept only common rows in the spatial joins. We check for any FinalIDs in NEPOS not in all_matches
  all_matched_ids <- unique(all_matches$FinalID2)
  if (!is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$State == state & nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  } else if (is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  }
  
  ## IS IT POSSIBLE TO INCORPORATE % OVERLAP TABLE HERE TO ACCOUNT FOR INSTANCES OF OVERLAP BUT NOT CENTROID CONTAINMENT??
  # Check to see if this is useful -- need to check Code 0 in map and see what these look like
  unmatched_pos <- data.frame('FinalID2' = unmatched_pos_ids)
  unmatched_pos$match_type <- 'None'
  unmatched_pos$match_type_code <- 0
  unmatched_pos$suggest <- 'Possibly delete'
  
  # Combine all_matches and unmatched_pos into main_df
  main_df <- bind_rows(all_matches, unmatched_pos)
  
  #### STEP 7: CLEAN UP AND SAVE ####
  # Join area and owner names to main_df
  # First, combine df1 and df2
  # Combine owner/area info from df1 and df2
  df1_pos_ids <- unique(df1$FinalID2)
  df2_pos_ids <- unique(df2$FinalID2)
  pos_ids_unique_to_df2 <- df2_pos_ids[df2_pos_ids %!in% df1_pos_ids]   # Get POS polygons only in DF2
  df2.ss2 <- df2[df2$FinalID2 %in% pos_ids_unique_to_df2, ]
  
  area_owner_names <- bind_rows(df1, df2.ss2)
  
  main_df <- left_join(main_df, area_owner_names[, c('FinalID2', 'UID2', 'NEPOS_AreaName', 'NEPOS_FeeOwner', 'SRC_AreaName', 'SRC_FeeOwner')],
                       by = c('FinalID2', 'UID2'))
  
  # Need to account for polygons pairs with very low acre ratio or % overlap that got coded into groups 2-8
  # In some cases, these should not be considered a match
  main_df[main_df$match_type_code %in% c(5, 6, 7, 8) & (main_df$ac_rat < 0.5 | main_df$ac_rat > 1.5) & !is.na(main_df$SRC_AreaName) &
            !is.na(main_df$NEPOS_AreaName) & !is.na(main_df$SRC_FeeOwner) & !is.na(main_df$NEPOS_FeeOwner) &
            (main_df$NEPOS_AreaName != main_df$SRC_AreaName | main_df$NEPOS_FeeOwner != main_df$SRC_FeeOwner), 'match_type_code'] <- 14
  
  # For % overlap, we can include codes 11-13 since these have % overlap calculated but do not have ac_rat
  # Due to not having a match in the spatial joins
  main_df[main_df$match_type_code %in% c(5, 6, 7, 8, 11, 12, 13) & main_df$PERCENTAGE < 20.0 & !is.na(main_df$SRC_AreaName) &
            !is.na(main_df$NEPOS_AreaName) & !is.na(main_df$SRC_FeeOwner) & !is.na(main_df$NEPOS_FeeOwner) &
            (main_df$NEPOS_AreaName != main_df$SRC_AreaName | main_df$NEPOS_FeeOwner != main_df$SRC_FeeOwner), 'match_type_code'] <- 14
  
  # Update the suggest for match type code 14
  main_df[main_df$match_type_code == 14, 'suggest'] <- 'Some match criteria met but poor match and names do not match. Possibly delete.'
  
  # Compare number of unique IDs in main_df and nepos after these additions
  # If the number in all_matches is higher, it could be because of subsetting NEPOS by state (border PAs)
  # Get both the number of unique IDs and the IDs themselves in case needed later
  main_df_ids <- unique(main_df$FinalID2)
  n_main_df_ids <- length(main_df_ids)
  print(paste0('Number of unique NEPOS IDs in main_df: ', n_main_df_ids))
  if (!is.null(state)){
    nepos_ids <- unique(nepos[nepos$State == state, 'FinalID2'])
    n_nepos_ids <- length(nepos_ids)
    paste0('Number of unique IDs in NEPOS: ', n_nepos_ids)
  } else if (is.null(state)){
    nepos_ids <- unique(nepos$FinalID2)
    n_nepos_ids <- length(nepos_ids)
    paste0('Number of unique IDs in NEPOS: ', n_nepos_ids)
  }
  
  # If number of IDs is higher in main_df than in NEPOS, print this and the "extra" FinalIDs
  if (n_main_df_ids > n_nepos_ids){
    print('Number of NEPOS IDs in main_df is higher than in NEPOS. This may be due to border PAs - further investigation needed!')
    extra_ids <- main_df_ids[main_df_ids %!in% nepos_ids]
    print('NEPOS IDs in main_df but not in NEPOS selection:')
    print(extra_ids)
  }
  
  # Save result! One copy w/ ac_ratio and PERCENTAGE and another with just the match_type and suggest columns
  if (save_csv == TRUE) {
    todays_date <- Sys.Date()
    write.csv(main_df, paste0('nepos_', source, '_match_table_', todays_date, '_full.csv'), row.names = F)
    write.csv(main_df[, c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest')],
              paste0('nepos_', source, '_match_table_', todays_date, '_min.csv'), row.names = F)
    print(paste0('Saved spatial match table for NEPOS and ', source, ' in working directory!'))
  }
  
  # Return main_df for graphing of results
  return(main_df)
}

# Function for spatial matching with Spencer's data
# This isn't treated the same as a standard source like TNC or PADUS
# I think it's worth thinking about how long we want to continue to use his data
# As of 2025, unique SRM dates are not updated automatically in NEPOS attribute update functions
# so using this function might not be necessary unless wanting to add SRM dates to more
# polygons than they currently are.
create_spatial_match_table_srm <- function(join_table1, join_table2, join_table3, join_table4,
                                       pct_overlap_table, nepos, source = 'source', state = NULL, save_csv = TRUE) {
  #### STEP 1: Read in and prep tables ####
  # Spatial join tables -- all joins only kept common rows, which means that only rows in the target fc
  # that had a spatial match in the join fc are present -- if a row in the target fc (polygon) is not
  # present, it did not have a join fc point inside it
  # 1:1 joins
  wd <- getwd()
  df1 <- read.dbf(paste(wd, join_table1, sep = '/'), as.is = TRUE)
  df2 <- read.dbf(paste(wd, join_table2, sep = '/'), as.is = TRUE)
  
  # 1:many joins
  df3 <- read.dbf(paste(wd, join_table3, sep = '/'), as.is = TRUE)
  df4 <- read.dbf(paste(wd, join_table4, sep = '/'), as.is = TRUE)
  
  # Percent overlap table
  pct.df <- read.csv(paste(wd, pct_overlap_table, sep = '/'), stringsAsFactors = FALSE)
  
  # DBF copy of the single part NEPOS attribute table
  # Since we only kept common rows in the spatial joins, we need to use this to identify NEPOS polygons
  # that did not have a match in any of the spatial joins
  nepos <- read.dbf(paste(wd, nepos, sep = '/'), as.is = TRUE)
  
  
  # Calculate acre ratio in each spatial join table -- NEPOS:source
  # Unlike other iterations of this script, both deleted_polygons and NEPOS have Area_Ac as the area field
  # which one is Area_Ac and Area_Ac_1 in the joins depends on which dataset is first in the join
  # For tables where POS is first, Area_Ac is the NEPOS area
  # For tables where deleted_polygons, is first, Area_Ac_1 is the NEPOS area
  df1$ac_rat <- df1$Area_Ac / df1$acres
  df2$ac_rat <- df2$Area_Ac / df2$acres
  df3$ac_rat <- df3$Area_Ac / df3$acres
  df4$ac_rat <- df4$Area_Ac / df4$acres
  
  # FinalID2 column of pct.csv formatted strangely, need to correct it
  colnames(pct.df)[1] <- 'FinalID2'
  
  # Subset each table to only needed columns -- UID2, FinalID2, Join_Count, ac_rat
  # For % overlap table -- UID2, FinalID2, PERCENTAGE
  df1 <- df1[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  df2 <- df2[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  df3 <- df3[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  df4 <- df4[, c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')]
  pct.df <- pct.df[, c('FinalID2', 'UID2', 'PERCENTAGE')]
  pct.df$UID2 <- as.character(pct.df$UID2)   # Not sure why it's an integer in this file but it is...
  
  #### STEP 2: Process polygon pairs where Joint_Count = 1 w/ bidirectional centroid containment ####
  # Join the 1:1 spatial join outputs
  # Parameter notes: inner join retains all rows in df1 (POS as target dataset)
  #    Using both UIDs as join fields ensures that the join happens correctly, and that we're
  #       only retrieving rows where centroid containment goes both directions between the polygon pair
  #    And joining only where Join_Count = 1 limits the join to only those rows
  #    (join counts greater than 1 will be handled later, along with 1:many join outputs)
  join1 <- inner_join(df1[df1$Join_Count == 1, ], df2[df2$Join_Count == 1, ], by = c('FinalID2', 'UID2'))
  
  # Drop unneeded columns and rename columns
  join1 <- join1[, -c(5:6)]
  colnames(join1) <- c('FinalID2', 'UID2', 'Join_Count', 'ac_rat')
  
  # Assign ac_rat_match based on whether the acre ratio is between 0.9-1.1 or not
  join1$ac_rat_match <- ifelse(join1$ac_rat >= 0.9 & join1$ac_rat <= 1.1, 1, 0)
  
  # Join the percent overlap table and add a column describing if the % overlap
  # falls within the threshold range
  join1 <- left_join(join1, pct.df, by = c('FinalID2', 'UID2'))
  join1$pct_overlap_match <- ifelse(join1$PERCENTAGE >= 90.0 & join1$PERCENTAGE <= 110.0, 1, 0)
  
  # Remove rows where either ac_rat_match or pct_overlap_match are NA
  join1 <- join1[!is.na(join1$ac_rat_match), ]
  join1 <- join1[!is.na(join1$pct_overlap_match), ]
  
  # Add 'match_type' field to describe the nature of the match for these polygons:
  # Bi-directional centroid match is present if the rows are in the join1 table, because we used both IDs to do the join
  # Acre ratio match is stored in ac_rat_match
  # Percent overlap match is stored in pct_overlap_match
  # Then based on the match type, populate 'suggest' column that suggests what action should be taken
  # match_type_code is just to help with plotting/querying because the match_type descriptions are long
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids, area ratio, and % overlap'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'match_type_code'] <- 1
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 1, 'suggest'] <- 'Good match - no action needed'
  
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids and area ratio'
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'match_type_code'] <- 2 
  join1[join1$ac_rat_match == 1 & join1$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type'] <- 'Centroids and % overlap'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'match_type_code'] <- 3
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type'] <- 'Centroids'
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'match_type_code'] <- 4
  join1[join1$ac_rat_match == 0 & join1$pct_overlap_match == 0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  
  #### STEP 3: Process polygon pairs where Join_Count > 1 ####
  # First, look for POS polygons that contain multiple source centroids (df1 and df3)
  # Get IDs of NEPOS that have multiple join -- this means multiple MA centroids are within one POS polygon
  multi_join_ids_df1 <- df1[df1$Join_Count > 1, 'FinalID2']
  
  # Extract rows with those IDs from DF3, which contains the 1:many join w/ NEPOS as target
  # These are POS polygons that had multiple MA centroids in them
  df3.ss <- df3[df3$FinalID2 %in% multi_join_ids_df1, ]
  
  # Add match type -- here we don't expect ac_rat to match because the join count is > 1
  # So the match is based just on POS containing source centroid
  df3.ss$match_type <- 'POS contains multiple source centroids'
  df3.ss$match_type_code <- 9
  df3.ss$suggest <- '1:many relationship - check geometry'
  
  # Combine 1:1 matches and 1:many matches -- joincols is all the columns for the 'full' output
  # Since df3 and df4 don't have these columns, we need separate sets of column names
  joincols_df1_df2 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 
                        'ac_rat', 'ac_rat_match', 'PERCENTAGE', 'pct_overlap_match')
  joincols_df3_df4 <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest')
  all_matches <- bind_rows(join1[, joincols_df1_df2], df3.ss[, joincols_df3_df4])
  
  # Next, look for POS polygons that that have a many:1 relationship with a source polygon (df2 and df4)
  multi_join_ids_df2 <- df2[df2$Join_Count > 1, 'UID2']
  
  # Get rows with these UID from df4, which contains the 1:many join w/ MA as target
  # These are the source polygons that contain multiple POS centroids
  df4.ss <- df4[df4$UID2 %in% multi_join_ids_df2, ]
  
  # Add match type for these rows
  df4.ss$match_type <- 'Source contains multiple POS centroids'
  df4.ss$match_type_code <- 10
  df4.ss$suggest <- '1:many relationship - check geometry'
  
  # Add these to the table of all matches
  all_matches <- bind_rows(all_matches, df4.ss[, joincols_df3_df4])
  
  
  ### STEP 4: Process polygons pairs where there is a 1:1 match but only in one direction ####
  # In other words, each polygon's centroid is not in the other, only one of them has this condition
  # First, look for POS polygons that are in df1 but are not in our all_matches table
  # This means that POS polygon contains a source centroid, but not vice versa
  # First, subset df1 to where Join_Count = 1
  df1.ss <- df1[df1$Join_Count == 1, ]
  
  # Then, exclude any rows in all_matches -- this will leave us with rows where Join_Count = 1 but didn't meet criteria for join1,
  # which included centroid containment in both directions (because we joined by both FinalID2 and UID2)
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  df1.ss <- df1.ss[df1.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  df1.ss <- left_join(df1.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  if (nrow(df1.ss) > 0){
    # Describe acre ratio and percent overlap
    df1.ss$ac_rat_match <- ifelse(df1.ss$ac_rat >= 0.9 & df1.ss$ac_rat <= 1.1, 1, 0) 
    df1.ss$pct_overlap_match <- ifelse(df1.ss$PERCENTAGE >= 90.0 & df1.ss$PERCENTAGE <= 110.0, 1, 0)
    
    # Remove rows where either ac_rat_match or pct_overlap_match are NA
    df1.ss <- df1.ss[!is.na(df1.ss$ac_rat_match), ]
    df1.ss <- df1.ss[!is.na(df1.ss$pct_overlap_match), ]
    
    # Add the match_type and suggest columns
    # For some of these groups, we add additional check b/c centroid containment is only in one direction
    # This suggests a less clear match and we want to check to see if owner or area name match if the acre ratio is very low
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres and % overlap within range.'
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. Acres match but not % overlap.'
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
    df1.ss[df1.ss$ac_rat_match == 1 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type'] <- 'POS contains source centroid but not vice versa. % overlap match but not acres.'
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
    
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type'] <- 'POS contains source centroid but not vice versa. No match for acres & % overlap.'
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
    df1.ss[df1.ss$ac_rat_match == 0 & df1.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
    
    # Join these results to all_matches df
    all_matches <- bind_rows(all_matches, df1.ss[, joincols_df1_df2])
  }
  
  # Repeat this process using df2, with contains source polygons that may contain a POS centroid but not vice versa
  all_matched_ids <- unique(all_matches[, 'FinalID2'])                 # Run this again to account for latest additions
  df2.ss <- df2[df2$Join_Count == 1, ]
  df2.ss <- df2.ss[df2.ss$FinalID2 %!in% all_matched_ids, ]
  
  # Join the percent overlap table
  # For the second iteration of matching w/ RI Local, after geometry updates, there was only 1 row in df2.ss
  df2.ss <- left_join(df2.ss, pct.df, by = c('FinalID2', 'UID2'))
  
  # Describe acre ratio and percent overlap
  df2.ss$ac_rat_match <- ifelse(df2.ss$ac_rat >= 0.9 & df2.ss$ac_rat <= 1.1, 1, 0)
  df2.ss$pct_overlap_match <- ifelse(df2.ss$PERCENTAGE >= 90.0 & df2.ss$PERCENTAGE <= 110.0, 1, 0)
  
  # Remove rows where there is NA for either acre ratio or pct overlap
  df2.ss <- df2.ss[!is.na(df2.ss$ac_rat_match), ]
  df2.ss <- df2.ss[!is.na(df2.ss$pct_overlap_match), ]
  
  # Add the match_type and suggest columns
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres and % overlap within range.'
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 5
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Good match other than unidirectional centroid containment - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. Acres match but not % overlap.'
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 6
  df2.ss[df2.ss$ac_rat_match == 1 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'Possible geometry shift - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type'] <- 'Source contains POS centroid but not vice versa. % overlap match but not acres.'
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'match_type_code'] <- 7
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 1, 'suggest'] <- 'Possible geometry update - check geometry'
  
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type'] <- 'Source contains POS centroid but not vice versa. No match for acres & % overlap.'
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'match_type_code'] <- 8
  df2.ss[df2.ss$ac_rat_match == 0 & df2.ss$pct_overlap_match == 0, 'suggest'] <- 'One centroid contained but otherwise poor match - check geometry'
  
  # Join to all_matches
  all_matches <- bind_rows(all_matches, df2.ss[, joincols_df1_df2])
  
  
  #### STEP 5: Handle polygon pairs where there is no centroid containment but there is some % overlap ####
  # Get all POS FinalIDs in all_matches
  all_matched_ids <- unique(all_matches[, 'FinalID2'])
  
  # Retrieve rows from pct df that have FinalID2 not in all_matched_ids
  pct.df.ss <- pct.df[pct.df$FinalID2 %!in% all_matched_ids, ]
  
  
  # Characterize match type based on % overlap
  # Groupings: >50% overlap, 25-50%, 5-25%, < 5%
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type'] <- '>50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'match_type_code'] <- 11
  pct.df.ss[pct.df.ss$PERCENTAGE >= 50.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type'] <- '20-50% overlap but no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'match_type_code'] <- 12
  pct.df.ss[pct.df.ss$PERCENTAGE < 50.0 & pct.df.ss$PERCENTAGE >= 20.0, 'suggest'] <- 'Significant geometry difference - check geometry'
  
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type'] <- 'Less than 20% overlap and no centroid containment'
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'match_type_code'] <- 13
  pct.df.ss[pct.df.ss$PERCENTAGE < 20.0, 'suggest'] <- 'Possibly delete'   # Same 'suggest' value as totally unmatched polygons
  
  # Join these results to all_matches
  join_cols_pct_df <- c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest', 'PERCENTAGE')
  all_matches <- bind_rows(all_matches, pct.df.ss[, join_cols_pct_df])
  
  
  #### STEP 6: Handle POS polygons with no match of any kind in source data ####
  # Compare number of unique NEPOS IDs in all_matches and NEPOS
  paste0('Number of unique NEPOS IDs in all_matches: ', length(unique(all_matches$FinalID2)))
  if (state %in% c('NH', 'MA', 'RI', 'CT', 'VT', 'ME')){
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos[nepos$State == state, 'FinalID2']))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else if (is.null(state)) {
    print(paste0('Number of unique IDs in NEPOS: ', length(unique(nepos$FinalID2))))   # In NEPOS v2_05 FinalID2 is named UID2
  } else {
    print('Cannot compare to NEPOS: ensure "state" is either state abbreviation or NULL for New England-wide data')
  }
  
  # In the previous steps, we used the 1:1 join tables to describe spatial relationships where there was a 1:1 match
  # and we used the 1:many join tables to describe the relationships that are not 1:1 matches
  # Spatial relationships not identified yet include 1) POS polygons not matching any source polygon, and 2) source polygons not in POS
  # For this step, we are only interested in #1 -- we will handle identifying new source polygons later using code from Landvest
  # At this point, we are focused on polygons already in NEPOS, looking for geom/attribute changes
  
  # To find POS polygons not matching any source polygon, we need to use the POS single part data
  # because we kept only common rows in the spatial joins. We check for any FinalIDs in NEPOS not in all_matches
  all_matched_ids <- unique(all_matches$FinalID2)
  if (!is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$State == state & nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  } else if (is.null(state)){
    unmatched_pos_ids <- unique(nepos[nepos$FinalID2 %!in% all_matched_ids, 'FinalID2'])
  }
  
  ## IS IT POSSIBLE TO INCORPORATE % OVERLAP TABLE HERE TO ACCOUNT FOR INSTANCES OF OVERLAP BUT NOT CENTROID CONTAINMENT??
  # Check to see if this is useful -- need to check Code 0 in map and see what these look like
  unmatched_pos <- data.frame('FinalID2' = unmatched_pos_ids)
  unmatched_pos$match_type <- 'None'
  unmatched_pos$match_type_code <- 0
  unmatched_pos$suggest <- 'Possibly delete'
  
  # Combine all_matches and unmatched_pos into main_df
  main_df <- bind_rows(all_matches, unmatched_pos)
  
  #### STEP 7: CLEAN UP AND SAVE ####
  
  # Save result! One copy w/ ac_ratio and PERCENTAGE and another with just the match_type and suggest columns
  if (save_csv == TRUE) {
    todays_date <- Sys.Date()
    write.csv(main_df, paste0('nepos_', source, '_match_table_', todays_date, '_full.csv'), row.names = F)
    write.csv(main_df[, c('FinalID2', 'UID2', 'match_type', 'match_type_code', 'suggest')],
              paste0('nepos_', source, '_match_table_', todays_date, '_min.csv'), row.names = F)
    print(paste0('Saved spatial match table for NEPOS and ', source, ' in working directory!'))
  }
  
  # Return main_df for graphing of results
  return(main_df)
}


#### COMBINING THE MATCH TABLES CREATED WITH ABOVE FUNCTIONS ####
# For any state, this is usually the state source, NCED, PADUS, and TNC
combine_match_tables <- function(state_abb, state_table, tnc_table, nced_table, padus_table, ri_local_table = NULL){
  state <- read.csv(state_table, stringsAsFactors = F)
  nced <- read.csv(nced_table, stringsAsFactors = F)
  tnc <- read.csv(tnc_table, stringsAsFactors = F)
  padus <- read.csv(padus_table, stringsAsFactors = F)
  if (!is.null(ri_local_table)){
    local <- read.csv(ri_local_table, stringsAsFactors = F)
  }
  
  # For 1:many relationships, refer back to POS_v2_08 which has ME geometry updates AND
  # match_type_code and geom_checked fields
  # which tell us whether to use the spatially matched polygon or the polygon in PolySource
  nepos_with_matching_fields <- read.dbf(nepos, as.is = T)
  nepos_with_matching_fields <- rename(nepos_with_matching_fields, PolySource_FeatID = PolySour_1)
  
  # Get unique ID of all POS polygons in ME
  all_nepos_state_ids <- nepos_with_matching_fields[nepos_with_matching_fields$State == state_abb, 'FinalID2']
  
  # Create dataframe to store combined results
  combined_match_table <- data.frame('FinalID2' = all_nepos_state_ids)
  
  # Join the PolySource, PolySource_FeatID fields
  combined_match_table <- left_join(combined_match_table, 
                                    nepos_with_matching_fields[, c('FinalID2', 'PolySource', 'PolySource_FeatID')],
                                    by = 'FinalID2')
  
  # Rename columns depending on state_abb and subset to the renamed columns
  # Then join to the combined_match_table
  if (state_abb == 'ME'){
    state <- rename(state, megis_id = UID2, megis_match_code = match_type_code, megis_pct_overlap = PERCENTAGE)
    state <- state[, c('FinalID2', 'megis_id', 'megis_match_code', 'megis_pct_overlap')]
  } else if (state_abb == 'NH'){
    state <- rename(state, nh_id = UID2, nh_match_code = match_type_code, nh_pct_overlap = PERCENTAGE)
    state <- state[, c('FinalID2', 'nh_id', 'nh_match_code', 'nh_pct_overlap')]
  } else if (state_abb == 'MA'){
    state <- rename(state, massgis_id = UID2, massgis_match_code = match_type_code, massgis_pct_overlap = PERCENTAGE)
    state <- state[, c('FinalID2', 'massgis_id', 'massgis_match_code', 'massgis_pct_overlap')]
  } else if (state_abb == 'CT'){
    state <- rename(state, ct_deep_id = UID2, ct_deep_match_code = match_type_code, ct_deep_pct_overlap = PERCENTAGE)
    state <- state[, c('FinalID2', 'ct_deep_id', 'ct_deep_match_code', 'ct_deep_pct_overlap')]
  } else if (state_abb == 'VT'){
    state <- rename(state, vt_id = UID2, vt_match_code = match_type_code, vt_pct_overlap = PERCENTAGE)
    state <- state[, c('FinalID2', 'vt_id', 'vt_match_code', 'vt_pct_overlap')]
  } else if (state_abb == 'RI'){
    state <- rename(state, ri_state_id = UID2, ri_state_match_code = match_type_code, ri_state_pct_overlap = PERCENTAGE)
    state <- state[, c('FinalID2', 'ri_state_id', 'ri_state_match_code', 'ri_state_pct_overlap')]
    local <- rename(local, ri_local_id = UID2, ri_local_match_code = match_type_code, ri_local_pct_overlap = PERCENTAGE)
    local <- local[, c('FinalID2', 'ri_local_id', 'ri_local_match_code', 'ri_local_pct_overlap')]
  }
  
  if (!is.null(ri_local_table)){
    combined_match_table <- left_join(combined_match_table, state, by = 'FinalID2')
    combined_match_table <- left_join(combined_match_table, local, by = 'FinalID2')
  } else {
    combined_match_table <- left_join(combined_match_table, state, by = 'FinalID2')
  }
  
  # Rename columns in TNC table and join
  tnc <- rename(tnc, tnc_id = UID2, tnc_match_code = match_type_code, tnc_pct_overlap = PERCENTAGE)
  combined_match_table <- left_join(combined_match_table, tnc[, c('FinalID2', 'tnc_id', 'tnc_match_code', 'tnc_pct_overlap')], 
                                    by = 'FinalID2')
  
  # Rename columns in NCED table and join
  nced <- rename(nced, nced_id = UID2, nced_match_code = match_type_code, nced_pct_overlap = PERCENTAGE)
  combined_match_table <- left_join(combined_match_table, nced[, c('FinalID2', 'nced_id', 'nced_match_code', 'nced_pct_overlap')], 
                                    by = 'FinalID2')
  
  # Rename columns in PADUS table and join
  padus <- rename(padus, padus_id = UID2, padus_match_code = match_type_code, padus_pct_overlap = PERCENTAGE)
  combined_match_table <- left_join(combined_match_table, padus[, c('FinalID2', 'padus_id', 'padus_match_code', 'padus_pct_overlap')], 
                                    by = 'FinalID2')
  
  # Save the combined match table with the date
  todays_date <- Sys.Date()
  write.csv(combined_match_table, paste0('nepos_', tolower(state_abb), '_matches_', todays_date, '.csv'), row.names = F)
}
